### ISSUE TITLE
系统调用章节文本错误

### ISSUE THREAD

**Issue by FEINIAO233** [linux-kernel-labs-zh/docs-linux-kernel-labs-zh-cn#62]
这里重复了
![image](https://github.com/linux-kernel-labs-zh/docs-linux-kernel-labs-zh-cn/assets/38801933/955cca04-953a-4d0c-8d07-dd560a06e648)

**Comment by hanyujie2002** [comment]
感谢 @FEINIAO233

**Comment by hanyujie2002** [comment]
已修正 #64
